import assert from "node:assert/strict";
import test from "node:test";
import { buildAdminErrorEmail, buildDailySummaryEmail, buildPasswordResetEmail, buildReminderDigestEmail } from "./email/email-templates";

test("email templates render branded html and plain text fallbacks", () => {
  const daily = buildDailySummaryEmail({
    workspaceName: "Work <Main>",
    userName: "Ash",
    now: new Date("2026-07-05T08:00:00.000Z"),
    tasks: [
      { title: "Close incident", status: "IN_PROGRESS", priority: "HIGH", dueDate: new Date("2026-07-05T00:00:00.000Z") },
      { title: "Document fix", status: "DONE", priority: "MEDIUM", dueDate: null }
    ],
    timers: [{ title: "Close incident", durationMin: 1, durationSec: 75, status: "STOPPED" }],
    aiSummary: {
      content: "## Top focus\n**Close incident** first.\n\n- Confirm customer impact\n- Document next action",
      providerLabel: "Groq",
      model: "llama-3.1-8b-instant"
    }
  });

  assert.equal(daily.subject, "What's Next? daily summary - Work <Main>");
  assert.match(daily.text, /AI daily briefing \(Groq \/ llama-3\.1-8b-instant\)/);
  assert.match(daily.text, /Open work: 1/);
  assert.match(daily.text, /Tracked today: 1m/);
  assert.match(daily.html, /Daily workspace summary/);
  assert.match(daily.html, /AI daily briefing/);
  assert.match(daily.html, /Generated by Groq/);
  assert.match(daily.html, /<h3[^>]*>Top focus<\/h3>/);
  assert.match(daily.html, /<strong[^>]*>Close incident<\/strong>/);
  assert.match(daily.html, /<li[^>]*>Confirm customer impact<\/li>/);
  assert.match(daily.html, /Work &lt;Main&gt;/);
  assert.doesNotMatch(daily.html, /Work <Main>/);

  const reminder = buildReminderDigestEmail({
    workspaceName: "Support",
    notifications: [{ title: "Overdue task", body: "Fix customer issue", tone: "warning" }]
  });
  assert.match(reminder.text, /Overdue task/);
  assert.match(reminder.html, /Reminder digest/);

  const reset = buildPasswordResetEmail({ resetUrl: "http://localhost:3000/reset-password?token=test", expiresIn: "30m" });
  assert.match(reset.text, /reset your What's Next\? password/i);
  assert.match(reset.html, /Reset password/);

  const alert = buildAdminErrorEmail({
    requestId: "request-id",
    statusCode: 500,
    method: "POST",
    path: "/api/tasks",
    route: "TasksController.create",
    startedAt: new Date("2026-07-05T08:00:00.000Z"),
    completedAt: new Date("2026-07-05T08:00:01.000Z"),
    durationMs: 1000,
    errorName: "Error",
    errorMessage: "Something failed",
    body: { title: "Bad task" },
    stack: "Error: Something failed"
  });
  assert.match(alert.subject, /API error 500/);
  assert.match(alert.html, /Admin alert/);
  assert.match(alert.text, /Request ID: request-id/);
});
